### ISSUE TITLE
Variable facet

### ISSUE THREAD

**Issue by MartinaSt** [PCMDI/input4MIPs-cmor-tables#55]
@durack1, I was asked by a user why the variable names are partly with a '-' and partly with a '_'. I would like to add that the variables are partly short names and partly CF-like long names. As a consequence the variable facet in the CoG portal is a bit confusing for users.

It would be good to tidy the variable facet a bit up:

- use only '_' and no '-'
- use abbreviations for chemical species (at the moment partly long names are in use).

What do you and Sasha think?

**Comment by durack1** [comment]
@MartinaSt that is a good point. The issue here is that the time pressure of making the data available limited the ability for the file names, variable names within the file, variable formats etc to be tweaked before publication. And so we've basically ended up with the best we could do in a very limited amount of time.

Moving forward it would be great to force standard_name alignment, generate a CMIP-style short name/acronym mapping for the ESGF interface etc etc, but we're stuck with what we have at the moment.

@sashakames do you have any comments to add here?

**Comment by sashakames** [comment]
I agree, but we lack the resources to make such a change.

**Comment by durack1** [comment]
@MartinaSt let's close this issue and aim to push all future contributions (that are not time sensitive) to go down the path of CF standard name registration, and then attempt to align all datasets with the current CMIP6 data request variable notation
